# Generated by Django 2.2.13 on 2021-09-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helevents', '0004_auto_20180109_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
