# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_add_data_source_past_events'),
        ('events', '0052_add_image_last_modified_time_index'),
    ]

    operations = [
    ]
