# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_add_data_source_past_events'),
        ('events', '0062_add_super_event_type_index_for_filtering'),
    ]

    operations = [
    ]
